stages:
  - build
  - push

image: docker:latest

services:
  - docker:dind

build_image:
  stage: build
  script:
    - echo "Building image from dockerfile"
    - docker build -t my_app:$CI_COMMIT_SHORT_SHA .
    - docker save my_app:$CI_COMMIT_SHORT_SHA > my_app_$CI_COMMIT_SHORT_SHA.tar.gz
  artifacts:
    expire_in: 1h
    paths:
      - my_app_$CI_COMMIT_SHORT_SHA.tar.gz

push_image:
  stage: push
  script:
    - echo "Login to DockerHub"
    - docker login -u $CI_USER -p $CI_PASSWORD $CI_HOST_URL
    
    - echo "Loading image from artifact"
    - docker load < my_app_$CI_COMMIT_SHORT_SHA.tar.gz
    - docker images

    - docker tag my_app:$CI_COMMIT_SHORT_SHA $CI_REGISTERY_NAME/my_app:$CI_COMMIT_SHORT_SHA
    - docker tag my_app:$CI_COMMIT_SHORT_SHA $CI_REGISTERY_NAME/my_app:latest

    - echo "Pushing image to DockerHub"
    - docker push $CI_REGISTERY_NAME/my_app:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTERY_NAME/my_app:latest

  dependencies:
    - build_image


